---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustdesk
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: rustdesk
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          hbbs:
            image:
              repository: ghcr.io/rustdesk/rustdesk-server
              tag: 1.1.12@sha256:9b1197d116f7bb4d3ad93a50bc1bc59ddb388de267df221a351f5ce10fac3dcf
            env:
              TZ: ${TIMEZONE}
              DB_URL: /db/db_v2.sqlite3
              ENCRYPTED_ONLY: "1"
              RELAY: "rustdesk-rd-relay.kube-apps.svc.cluster.local:21117"
            command: ["hbbs", "-r rustdesk-rd-relay.kube-apps.svc.cluster.local:21117"]
            ports:
              - containerPort: 21115
                name: rd-nat
              - containerPort: 21116
                name: rd-hole
              - containerPort: 21116
                name: rd-id
                protocol: UDP
              - containerPort: 21118
                name: rd-ws
          hbbr:
            image:
              repository: ghcr.io/rustdesk/rustdesk-server
              tag: 1.1.12@sha256:9b1197d116f7bb4d3ad93a50bc1bc59ddb388de267df221a351f5ce10fac3dcf
            env:
              TZ: ${TIMEZONE}
            command: ["hbbr"]
            ports:
              - containerPort: 21117
                name: rd-relay
    # 21115 TCP for NAT type test
    # 21116 TCP TCP hole punching
    # 21116 UDP heartbeat/ID server
    # 21117 TCP relay server
    # 21118 TCP for web socket if you want to run web client
    service:
      rd-server:
        controller: main
        ports:
          rd-nat:
            port: 21115
            protocol: TCP
          rd-hole:
            port: &port 21116 # ID server
            protocol: TCP
          rd-id:
            port: *port
            protocol: UDP
          rd-ws:
            port: 21118
            protocol: TCP
        # externalTrafficPolicy: Local
      rd-relay:
        controller: main
        ports:
          rd-relay:
            port: 21117
            protocol: TCP
        # externalTrafficPolicy: Local

    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: rustdesk-config
        globalMounts:
          - path: /db
            subPath: hbbs
          - path: /root
            subPath: root
