---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustdesk
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: rustdesk
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        containers:
          hbbr:
            image:
              repository: ghcr.io/rustdesk/rustdesk-server
              tag: 1.1.12@sha256:9b1197d116f7bb4d3ad93a50bc1bc59ddb388de267df221a351f5ce10fac3dcf
            env:
              TZ: ${TIMEZONE}
            command: ["hbbr"]
            ports:
              - containerPort: 21117
                name: rd-5
              - containerPort: 21117
                name: rd-6
          hbbs:
            image:
              repository: ghcr.io/rustdesk/rustdesk-server
              tag: 1.1.12@sha256:9b1197d116f7bb4d3ad93a50bc1bc59ddb388de267df221a351f5ce10fac3dcf
            env:
              TZ: ${TIMEZONE}
              DB_URL: /db/db_v2.sqlite3
              ENCRYPTED_ONLY: "1"
              RELAY: "rustdesk-hbbr.kube-apps.svc.cluster.local:21117"
            command: ["hbbs", "-r 10.10.30.20:21117"]
            ports:
              - containerPort: 21114
                name: rd-1
              - containerPort: 21115
                name: rd-2
              - containerPort: 21116
                name: rd-3
              - containerPort: 21116
                name: rd-4
                protocol: UDP
              - containerPort: 21117
                name: rd-5-relay
              - containerPort: 21118
                name: rd-6
              - containerPort: 21119
                name: rd-7-relay
    # 21114 TCP for web console, only available in Pro version
    # 21115 TCP for NAT type test
    # 21116 TCP TCP hole punching
    # 21116 UDP heartbeat/ID server
    # 21117 TCP relay
    # 21118/21119 TCP for web socket if you want to run web client
    service:
      hbbr:
        controller: main
        ports:
          rustdesk-5:
            enabled: true
            port: 21117 # Relay server
            protocol: "TCP"
          rustdesk-6:
            enabled: true
            port: 21119
            protocol: "TCP"
      hbbs:
        controller: main
        ports:
          rd-1:
            port: 21114
          rd-2:
            port: 21115
          rd-3:
            port: &port 21116 # ID server
          rd-4:
            port: *port
            protocol: UDP
          rd-5-relay:
            port: 21117
          rd-6:
            port: 21118
          rd-7-relay:
            port: 21119

    route:
      hbbr:
        hostnames: ["hbbr.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - port: 21117
                name: rustdesk-hbbr
      hbbs:
        hostnames: ["hbbs.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: rustdesk
        rules:
          - backendRefs:
              - port: 21116
                name: rustdesk-hbbs
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: rustdesk-config
        globalMounts:
          - path: /db
            subPath: hbbs
          - path: /root
            subPath: root
