apiVersion: v1
kind: Secret
metadata:
    name: rustdesk-secrets
    namespace: kube-apps
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:GCFXGi2OhlA=,iv:9LCyaNYrcHVa+FQK5w4N/r4xPtSjM2qdw4oUHY5UwHE=,tag:4koSGFTT1zCFv6KyygMnuA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2M9YFKJVv9+PzNdqe6D7MWNpwzJytKMZeSVXEOOehUDO,iv:5oPIk0mhILI8k1rkUwqFuuH8IZTE6Ca2B3s4+iHounM=,tag:HeNRxLb5vybRqLt09h6ihA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:q8qQuQ==,iv:FhwLlTKfGwFFfmIWCtXNfcb9cItkMvpgv2KqY4GjcLo=,tag:NF4aiCogOFiaO04F0qy9qQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TRbVkQ==,iv:h9meYY54EDG3ElBsPP70tIOkRmwXmlihhtIspH2/6ck=,tag:uO3y0cQft91BwT7ZMZOr1g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mSC5tQ==,iv:4udw5VQlXUnTPa7hsi4CMvSsv9Ye6ozwK8hf50diwa8=,tag:j56oMmIjoNWnfG9odT/biQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweDZZZnNJMFJmUVVRZFlq
            RlpKMFpyZzRQSk1vV1pvVytkNGJtVVUxRXlVCnZnbEZaZG5Ld2FITDlBa1phOXFk
            R0Z5UzlZZkh1QWpCdFNWN0F0cG5nejgKLS0tIG1rL3pDMTZ0TTJBblRxdkQxTVpu
            K3c3dlNlQ0l3VjhacVFONVdIM3BSOXcKwEfiPvFzy9ju8XHXYJLXJpG9El9SlQXc
            XUNzp6zHHcCEIflIpEJssLFuq9zxCFXk3CoFpk/2PNi8MiOIKIl/qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T14:15:18Z"
    mac: ENC[AES256_GCM,data:1La9ounUDcRdeQj9pdEbDOuM7YWOPsXHG2x/sz7MuDsJ6tn9vIhZSHqlCt1PlF1fkuQZ6OnigA6AeCZz/lnKYcv0YpSRcxx0dhiS2rSBU5kXe/3CwsG4zk6Q4Mdu9scKKUgeHDHWNGKGsLjNGbvPEEGDwVZDXltmyfejyXWhfVc=,iv:fPGGKXwzCh5Cmrou+Xlkw6z+8uYDoDaBdMjFbQ94/J8=,tag:SFOrovq9mYZ0dSpT3CeYng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
