---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: rd-udp
spec:
  hostnames:
    - "rd.${SECRET_DOMAIN}"
  parentRefs:
    - name: external
      sectionName: rd-udp
  rules:
    - backendRefs:
        - name: rd-id
          port: 21116
