---
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: rd-udp
spec:
  parentRefs:
    - name: external
      sectionName: rd-udp
  rules:
    - backendRefs:
        - name: rd-id
          port: 21116
