apiVersion: v1
kind: Secret
metadata:
    name: sftpgo-secrets
stringData:
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:WSG56PbAaDSZG2pGBtGGzkVbWFJFo6CHPxXJgAX361lW,iv:LANXetiq9wpC5PrsC9JK48jscO5Tt0aEyTR471U1DIQ=,tag:/6LthX0aiDJWxeoXYfx+Xw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:NRqTIg==,iv:DkibV0FIt+qdvqWbGoMi+za8TzF4xK0J7uQWQGEHUQU=,tag:XYffYzG7HWCzZuA/RSt0/g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:K/lGxQ==,iv:BqbhfNBxsK87X8SZhIY5COeEs41M1Vcs8KR+YTGGpSM=,tag:NRMEFZzU4GSpevJBfTf8lA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:cXVFhQ==,iv:eWrxqWa6WYGV4tBPoxFbKnj89Z33juSHLGiC+iI29ME=,tag:a0ExHM3ZN0jnnEIUZNISYw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Vu8mEJZl,iv:L+Br5I8twHR6PLvCxUrNBzdWTcgLHomk6sYU61/hmYA=,tag:FZgdJ2eMb/5sYOE6y6EJXA==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:6rYIncw=,iv:qKsn8UqsVtcMzQjGlMCkqsrD+NQ4LCZ7mIK4DczhJUo=,tag:PsYo4RIkCGoG6kYg+sTfDg==,type:str]
    ADMIN_PASS: ENC[AES256_GCM,data:uk+vZSrvxjwPGlaVHk8xKA==,iv:bEbRdZoT61XpFEVg8jDpmD2xMPSbLVUh4tMHXBfB4dw=,tag:0mLOssAOR0IEc3qBRtJgvA==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:JMPLsNPlwzVsJaBmfLcGv9iggdtteHMzdkmk7Dn8qhIxE5ZRufZNT0/wOO6oIB4hwJoHO9sNAoj91IjDQCZT2Sim/pAyXSSz,iv:znAqVs7dilhjbzwp/qaIWKSQazhAd8JzjqOviODCguA=,tag:Nrtl/wTEaWCVvhyei9KMDQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:tbEhcMlwYqwvz2zVU287eIrDM0cD1JkT1KvXJ2jFgX0hVsC/0SxJfv+elhf2pfG/xyYvD163OrEbHMr7stYzlVM6NISRiB/5,iv:MIoXU63YpqIaKcJYNLGe0w4Hro9Xsxd8F4+vvWvBxZw=,tag:8k/c5dOKf/IOmNHdwd4cOw==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cWZiNmpha3RHSnlpU1BQ
            MHFuMCtUaE9QOHMwZm5XeEk5cE9mTHdWTGdZCnZEZlYxNUQ2ZjlpMFhHSlpRTEdD
            bkc4VlRiM1c3VlpuRmJXK0ZhVE16MEUKLS0tIG1qNXl4ekdHbmY3bzNlc2w2US9m
            bEFGOEdBN0cxL01zUHV6Sno0V2N2WTQKAe1tq1e9lptbFpwdWmh0LtRjcNYMVgh0
            3/Ny0jVJlbNeIbCSfDLEohCWjNhclzqS/f7Ts0Sgh9QbSFLkFgWp+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:32:13Z"
    mac: ENC[AES256_GCM,data:U6Dejh+M1AyttltSJWfG6X8RbMjDxuGY82a/HLh0tVMyK81XhaV0Aj0+c1qqbwtk2lymzN2D6lAkotvP+HevXNRKVvcsfHTslnF+FVYwpNQmsN+jYoNlmaYRcUC/+/WOgrYyo3nW6f1kIdsA411CRm7Q+l27WQLokVD4TxMlKjo=,iv:kIYfacrEKKk/y0b0YbDS7Jm3JZtO0VO8wqNaPyYr6/w=,tag:HzmxqyV4KJhdkJm03H/uZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
