---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sftpgo
spec:
  components:
    - '../../../../components/archive'
  interval: 30m
  path: ./kubernetes/apps/kube-apps/sftpgo/app
  prune: true
  wait: true
  dependsOn:
    - name: storage-volumes
      namespace: storage-system
    - name: cluster17
      namespace: db
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      NS: kube-apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-apps

