apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: kube-apps
stringData:
    #ENC[AES256_GCM,data:SVo=,iv:jidGwxgCn7KpkcdAfgjwRbA5J6qIe4t6gACPW/AeOzE=,tag:tEwEjOgMFpWI8EeHkF3Zog==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9B1CRAw=,iv:DEU5SMF5ArPnscDHBpXIwsFD1yNRiVridYPOVJcgLnI=,tag:WlPX0sGw/uq/RZeBa7zWvw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2M9YFKJVv9+PzNdqe6D7MWNpwzJytKMZeSVXEOOehUDO,iv:5oPIk0mhILI8k1rkUwqFuuH8IZTE6Ca2B3s4+iHounM=,tag:HeNRxLb5vybRqLt09h6ihA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:q8qQuQ==,iv:FhwLlTKfGwFFfmIWCtXNfcb9cItkMvpgv2KqY4GjcLo=,tag:NF4aiCogOFiaO04F0qy9qQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TRbVkQ==,iv:h9meYY54EDG3ElBsPP70tIOkRmwXmlihhtIspH2/6ck=,tag:uO3y0cQft91BwT7ZMZOr1g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mSC5tQ==,iv:4udw5VQlXUnTPa7hsi4CMvSsv9Ye6ozwK8hf50diwa8=,tag:j56oMmIjoNWnfG9odT/biQ==,type:str]
    #ENC[AES256_GCM,data:6DIx,iv:X5ijwkW36eB8C0Y9rzOhReg99sT9ic14GgAgdQ8IpWg=,tag:MzVGdf6bVmVKrHIhKPKXMg==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:pSF8P/xydiu5VVpo1lsCLcgt2jYDbj+2h+Iz8hjNc84=,iv:FxPp2AcrZ/AsjCHoP05kU9Un5i0LokR6yHNsNmOJMxI=,tag:nobWPiufQgFf044UihToCg==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:soAXk8OvWuLZ7heNqtLbDQ==,iv:uTVbFAPIlTED+FF5W4k8VAE88sjashlJf6N8EjMXiOw=,tag:eqRIkbovP+dqQp3KL/vBSw==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:lCh3AGveJg3MVVnGa2oUQl+t,iv:W/cEPJ4XAy6aOrKz+PgtNsoT/yJ0imS/mdk72FfibJg=,tag:myqYQPxUxKrOxBrRplMm2A==,type:str]
    LDAP_USER_EMAIL: ENC[AES256_GCM,data:Kfp9TwXRga+VeSpaGSYgz0Nm+KA=,iv:66XBTlwK1Snekyzy+82ilv/87mIdnv8mFexMyt0hrQg=,tag:62sA3Pe9ewfuThD27HB1+A==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:Fk4ELjND25H8omJGXCKA0jhtqR5inFS0SmdLi148le8=,iv:yoWNOc+m3gZjeU4YM4FNC58BtI7l53t2S1sLrtDxT/I=,tag:LRLKm2abJVWZBIQXldyzJQ==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:vj3nSKFOQr1Jb0PFuOV1oePsILDHu0WOF0N396ZP9wLvh1osqC+bPe0FmvHi+iP7W7V2uJTKQsGxfVwL,iv:jY5e+PDfrAwapJrPiKWTsJOc5StjNNY1xSsupuoEckI=,tag:N2pnkaFvzC+Btct2/j/Ihg==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweDZZZnNJMFJmUVVRZFlq
            RlpKMFpyZzRQSk1vV1pvVytkNGJtVVUxRXlVCnZnbEZaZG5Ld2FITDlBa1phOXFk
            R0Z5UzlZZkh1QWpCdFNWN0F0cG5nejgKLS0tIG1rL3pDMTZ0TTJBblRxdkQxTVpu
            K3c3dlNlQ0l3VjhacVFONVdIM3BSOXcKwEfiPvFzy9ju8XHXYJLXJpG9El9SlQXc
            XUNzp6zHHcCEIflIpEJssLFuq9zxCFXk3CoFpk/2PNi8MiOIKIl/qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T19:34:28Z"
    mac: ENC[AES256_GCM,data:9sYGD3RLeAMU6LMU94XzdwCTlrkCEqAscTPXigZjWtxE0VLsR6hqgGLjjiohqNlGFIfge88nlfwBzp35g+oXFk8LWGrkjv5BYNtFB9Yw/4qQb005qs6CJef6hwZtbbPIbbGSGqbyp29qzkmQyqFP3cAlkW9gA3i/QrWPJNs0hAI=,iv:xDNtzNbYUoCltILdVFyVj0auGOKLX1Nm5uo580YVMAo=,tag:ewkQPN9r+xFJwGjMQWS4dA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
