apiVersion: v1
kind: Secret
metadata:
    name: immich-db
stringData:
    HOSTNAME: ENC[AES256_GCM,data:wqZ+zbhJaFeubJnUo+5O4sVih27v2IE0I9TjdHl994yq,iv:DozIRw2W9Yej7PPgKFKLVypaZc6PNNu0g9SAyxg6fmg=,tag:qav8hf9ES4/ctCr21MniSw==,type:str]
    USERNAME: ENC[AES256_GCM,data:cO35JQ==,iv:qyL6TCNo4g+drEeDgUG5qdlX/94rztHTH0RzR28NRp0=,tag:Ub/h0FvSuVrrqyUuQWf/Fw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:pgpiNQ==,iv:Uyq6ds3imVfBH/SGwxKqIdrbiffghUb5+UQ8I/+DkwY=,tag:GwsINdXvpewHEB31Hk+ilA==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:1rVQbNy0,iv:UVLvnh6XZzWM6n52l3q3Cuxy7vRaBuXzpUnItjs4BzE=,tag:7+pWcXQmkRyKXPSBQTulXg==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd2lYeEo1UkgyU0QyMDA4
            TUwvVGVKN0ZCTU12MVUvZUpqU1g5Q1oxUW1jCm9abHg3OWtLZzRMZnowaFJvenVQ
            YUVnOERtQ0g1dnBzYzluWnR3OUJ5eUkKLS0tIEZLaVE0TmtBeHY5TyticENqTTlG
            OFk5UUZwQm9hS1JYYWRtOGFWOWhLK0UKMYXcDk8eajCyQPdn/5VxO85Wm9h4O3r5
            NiLmwgk5wPpyf3v+ZyE5gztjnRuXceXcLXGBjvF/E4QJo4vEoFhhrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T15:34:26Z"
    mac: ENC[AES256_GCM,data:6rNXfrAM99NfU0atMY2rSmnMiYchUBX1JD0GIF7DDKeoPeTMDQ0o62f9863XxY1B2EoNCImYMR6HrFa9SffY/Zwe2pmRo9YEtcBSVX6at3zP7oiOncHuUAfpgC6iRqeTjWUjnN+9ksG/9wdT9cN27/Y1b62scmLEFqhOImm6GsM=,iv:pu7F8+RWd83S2qqEccoo2XbMTTMtSL4sMX37NTr+IzU=,tag:JkuSGqbZnC5kgB/7U18F4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
