apiVersion: v1
kind: Secret
metadata:
    name: immich-db
stringData:
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:QebFkS995D96qYmd8rzsgvXr1s5dW7KQuyIpJenUhrfe,iv:qGJv9KyV8ajNX7FvdjEJ2P5Y0ByZ9a8ceaZ1DF/o/wk=,tag:3I8cdoGzQ06IPqp4e/4Ruw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:W97t0Q==,iv:aL7vweL2SOUVv1cqtyx6i81UCJFwgn2COrXe5hSkeHM=,tag:OeTTmHSYVnK5R0PpILc11g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:txYEMw==,iv:srz5+UCiDLPQxj05gj/NWwWfinKsv4GGHDaRtqPXqjI=,tag:v1IkXxm7Vzn9t/Q4thsD3A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:XNVo0Q==,iv:3w3vSQEIilEvf/yP6DTNwBdJDp9UetAqgfHLQPR+GUA=,tag:DTiTk9HLx9WTt6915Cq1RQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:MWnuOFzQ,iv:QhuTUPTQ8RyJHeqXkfvfvYrZbTw3lxtR+JAZuHkl0Q4=,tag:TMSn5vR33hwwobJNUvdUMA==,type:str]
    HOSTNAME: ENC[AES256_GCM,data:1L4blk5pqwYZp0SfAsNCkZyW4054b+nXK+4frxg/gebN,iv:hIKa/gHfLdRT9xlYY/HxmLn5qPGXxhL8oUHb8QuP1+A=,tag:JKbtcLFQ1r7FpsrHl1H68A==,type:str]
    USERNAME: ENC[AES256_GCM,data:cO35JQ==,iv:qyL6TCNo4g+drEeDgUG5qdlX/94rztHTH0RzR28NRp0=,tag:Ub/h0FvSuVrrqyUuQWf/Fw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:pgpiNQ==,iv:Uyq6ds3imVfBH/SGwxKqIdrbiffghUb5+UQ8I/+DkwY=,tag:GwsINdXvpewHEB31Hk+ilA==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:1rVQbNy0,iv:UVLvnh6XZzWM6n52l3q3Cuxy7vRaBuXzpUnItjs4BzE=,tag:7+pWcXQmkRyKXPSBQTulXg==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd2lYeEo1UkgyU0QyMDA4
            TUwvVGVKN0ZCTU12MVUvZUpqU1g5Q1oxUW1jCm9abHg3OWtLZzRMZnowaFJvenVQ
            YUVnOERtQ0g1dnBzYzluWnR3OUJ5eUkKLS0tIEZLaVE0TmtBeHY5TyticENqTTlG
            OFk5UUZwQm9hS1JYYWRtOGFWOWhLK0UKMYXcDk8eajCyQPdn/5VxO85Wm9h4O3r5
            NiLmwgk5wPpyf3v+ZyE5gztjnRuXceXcLXGBjvF/E4QJo4vEoFhhrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T14:32:48Z"
    mac: ENC[AES256_GCM,data:OAN4gd6plnUC1NsQ0SO5T0zaSIb89jtwXF6eNR/4IM/vjbmjbCe49ZowwH4AmVx1dQaj9ZAABEmUTLYMWxG0HuOCJwfj+Uu72maJi10Ni8GlP2oDotcAi7EF4NVZ/5o5hVjYsRfozicSUoxgUIYZwzQoMHtuJ5Q3k0LucQ3HLFQ=,iv:nTM6wxW8AlMI/FTfUjyAXriv1votsZhUaadArxv7770=,tag:Zm62aAVPh3bYsZcKxGJF4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
