apiVersion: v1
kind: Secret
metadata:
    name: immich-db
stringData:
    HOSTNAME: ENC[AES256_GCM,data:dLGX2R0pR2NzCiaQB67ozNPSVxlHxJWN0gCHGrVtVnWFs7u8LQDSKlQ=,iv:Wo/rjOo/WaQWAVvRGjJEazdUeZ/MbzBi0O5LYkp7qqI=,tag:GLCwkmR/aszqNMqvFEWEKA==,type:str]
    USERNAME: ENC[AES256_GCM,data:cO35JQ==,iv:qyL6TCNo4g+drEeDgUG5qdlX/94rztHTH0RzR28NRp0=,tag:Ub/h0FvSuVrrqyUuQWf/Fw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:pgpiNQ==,iv:Uyq6ds3imVfBH/SGwxKqIdrbiffghUb5+UQ8I/+DkwY=,tag:GwsINdXvpewHEB31Hk+ilA==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:1rVQbNy0,iv:UVLvnh6XZzWM6n52l3q3Cuxy7vRaBuXzpUnItjs4BzE=,tag:7+pWcXQmkRyKXPSBQTulXg==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd2lYeEo1UkgyU0QyMDA4
            TUwvVGVKN0ZCTU12MVUvZUpqU1g5Q1oxUW1jCm9abHg3OWtLZzRMZnowaFJvenVQ
            YUVnOERtQ0g1dnBzYzluWnR3OUJ5eUkKLS0tIEZLaVE0TmtBeHY5TyticENqTTlG
            OFk5UUZwQm9hS1JYYWRtOGFWOWhLK0UKMYXcDk8eajCyQPdn/5VxO85Wm9h4O3r5
            NiLmwgk5wPpyf3v+ZyE5gztjnRuXceXcLXGBjvF/E4QJo4vEoFhhrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T15:39:19Z"
    mac: ENC[AES256_GCM,data:E0wg6iEF2B9IVX+NK6Qvb9JKZMlFn/wdpcgLMEcdqpKNSUoIosJJpGR70cBFhBXzTIcBQj5cg4V03kUcrHGT5euji7rDAiA8DpxI5RtPTfyt/VmM75rjc6c89Ansd2qBxE36y0vxzRDqA75pSBYSRJjDGmUASjtOn+iFFngBfaQ=,iv:9bYrzOT/BvIOyy4N+Jbkd+4NDGu8Arpuiz9JznzXDqw=,tag:fB+tRxeQ5kqNhAB6hxeZqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
