---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-${PVC_NAME:=config}
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${APP}-restore
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:=1Gi}
