---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
spec:
  components:
    - '../../../../components/volsync'
  interval: 30m
  path: ./kubernetes/apps/kube-apps/immich/app
  prune: true
  wait: true
  dependsOn:
    - name: volsync
      namespace: storage-system
    - name: cluster17
      namespace: db
    - name: dragonfly
      namespace: db
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
    substitute:
      APP: *app
      PVC_NAME: 'library'
      VOLSYNC_SCHED: "0 */12 * * *"
      VOLSYNC_CAPACITY: 100Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-apps
