---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubevirt
  namespace: virt
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: kubevirt
      interval: 30m
  values:
    resources:
      - apiVersion: kubevirt.io/v1
        kind: KubeVirt
        metadata:
          name: kubevirt
          namespace: virt
        spec:
          certificateRotateStrategy:
            selfSigned:
              ca:
                duration: 168h
                renewBefore: 48h
              server:
                duration: 72h
                renewBefore: 48h
          configuration:
            developerConfiguration:
              featureGates:
                - HostDevices
                - VSOCK
                - KubevirtSeccompProfile
            permittedHostDevices:
              usb:
                - resourceName: kubevirt.io/inelo
                  selectors:
                    - vendor: "0403"
                      product: "f6c8"
                - resourceName: kubevirt.io/token
                  selectors:
                    - vendor: "096e"
                      product: "0807"
            smbios:
              sku: "${CLUSTER_NAME}"
              version: "1.0.0"
              manufactorer: "SideroLabs"
              product: "Talos"
              family: "kvm"
          # Patch the DeamonSet as workaround for https://github.com/kubevirt/kubevirt/issues/16264
          # Otherwise kubeapi will alert for client cert errors recorded in metric apiserver_client_certificate_expiration_seconds_bucket
          customizeComponents:
            patches:
            - resourceType: DaemonSet
              resourceName: virt-handler
              patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-handler","volumeMounts":[{"name":"kubevirt-virt-handler-certs-ext","mountPath":"/etc/virt-handler/clientcertificates","readOnly":true}]}],"volumes":[{"name":"kubevirt-virt-handler-certs-ext","secret":{"secretName":"kubevirt-virt-handler-certs"}}]}}}}'
              type: strategic
          imagePullPolicy: IfNotPresent
          infra:
            replicas: 1
          workloads:
            replicas: 1
          workloadUpdateStrategy: {}
