---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vms/testvm.yaml
  # - ./vms/truenas.yaml
  - ./vms/win10.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./kubevirt-operator.yaml
