---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster17
spec:
  interval: 30m
  path: ./kubernetes/apps/db/cluster17/app
  prune: true
  dependsOn:
    - name: cnpg
    - name: plugin-barman-cloud
    - name: minio
      namespace: storage-system
  postBuild:
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: db
