apiVersion: v1
kind: Secret
metadata:
    name: auth-db
    namespace: kube-system
stringData:
    storage.postgres.password: ENC[AES256_GCM,data:ZVZbHA==,iv:mwnkcAeh4kNZ9WCRt/sMNo/LsoJ7gFW3d1dBqYK2oG4=,tag:h5hAPHhf3p4JhcM2zeMvtA==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNmp0Y3l1UkZ6RDczTjJF
            T2tRdFZIRVlQTjQxOEljaVpnek04c09pZjBFCkc5TVI0RTNOdytZcEN2WkptQkpu
            cnh0ZFJEYzZpZ2crUWs3TG90ckVLcTgKLS0tIHBIUjJzTEc0R0tqZlcrcGRUTVcz
            Q2l6M3pGMzNPdHE0SWNmNzJwTzZTdWcK1hiXqxILIeFloFK1flk6ILFwMOGAmIky
            Hwrpg/d9qFX87OM7Z+eSv1Rwf1C6jIZP4QnI8qnazUZW6ALMjxeXjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:08:00Z"
    mac: ENC[AES256_GCM,data:OgdCian3mQmEOtIAOq9Eqcc4mvOwr4eDCwvHCowei8RJkDU43wzFHvccw8gZ4tLTpAAtlVnIfooEJ3eAD43+KGPmibwcbdH5Ed1PGMtvklrPQyIt8iH7K6btDjfpM/SLzQdnvkTm6n1hbx2SwUGgt7mrmzxDlg5enICLJhhMBLI=,iv:oMnNXB5tY3RCPCWuwdtBcn9ANefzjo/IhxNTnMChq4o=,tag:ueRXndWnlquM3q4ASS4bvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
