---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./db.sops.yaml
  - ./helmrelease.yaml
  # - ./httproute.yaml
  - ./ocirepository.yaml
  - ./restic.sops.yaml
  - ./secrets.sops.yaml
