apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: kube-system
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:OehW+o7KETI+w2PCVQM04+7LvgJ3DY6XUnB0DJKV2V4vBfAB76scONHWHDi1VXt2eNx/dAnK2u+R332kXoW3dPWNxF3tz6zKLCO/4RnXfyO1zz6EbiBt6C4ZM0kPkU7C7fEd2VFU13rSPzPCQ/sHugscevLNCidJnGOfC6LTmkc=,iv:C6PCyZTCDKR/FfVWA+CZ3+arhMqcSntX9ughEZHhcmY=,tag:Ixr59oWth6vqQFKp1yykKg==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:YFXurG9yha/JDqCxWFBiGx2C9o4sRDgO2d4BEbt8fbDSqyhcgUpz5GfOggVCHtJyV8DTVS1HzLyWCZQ8YkUK1kchlyHMAapV/yxHny+oFXr+K1dkTAkyDT3c/TtNF+gHERITbaIlLmeEXK/1JsYPoNcv8f5TBngKLZf7DmTME+s=,iv:d69TJRkuCbJV8EbxEjYQq89jfyGHn4KOa3LnCgXYF+4=,tag:GmKTYy2ARmqFMnj+aanQGA==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:34gqSSnIph3SxF72CjUXHKlvKen9+4TOVZIe9/diGw9wpG8HdRb2ZhIb8lK7b6Vypy/lIPxQ9es5pTZOPMQsR3sA2DtpUWUY+LcpJFvgPxNRnt36elH641Ol8NYqCM9zYsCKty8x/6Mi3myDni3PSDugwzWy+XEYPvThMAFmhes=,iv:AJ0SslQCWheYPNWEO+CT2lRFVwyDhfVPoERRN4pz07s=,tag:viR47lTdtWqlQpBgVY18Wg==,type:str]
    session.redis.password.txt: ENC[AES256_GCM,data:eWvxIKBRU1cP8tCQdiSTJDeVVNrfi4JBVU+sCP0G5QkHbMHyziRfIT0Zkl6Cw2s9SJ/lP2n423Gg2Qig6tOncjn4hdLFLBvlai31eWYGYi9XA+AyRQ4PyVAzSvDMIM++YvYR0JyxrziT8R5X1kPY57IcUeiqshJJHLGD+WoAg9o=,iv:y7nr3yjmJIjlSa6xgBJPv45MutAN8to2BSgRp9tGUyY=,tag:frO0rLM9fTXxh5z8D6zKTw==,type:str]
    storage.postgres.password.txt: ENC[AES256_GCM,data:L9XJyvI1d99OEySlc68F4lfNSNwEtrUdRRa1G85ntiX7k9Qx5D0vzFwgW+vdNtoS+wMVwpWqcNzAj7gQ5x+u6ZqSUgE3wW8rmhfvQZmiqg5dmTO40fPOFOPxW5DaHu1BWNRrkcV1fINpW8LJXbmkxzsxGUZP7lolqHRlqeuCL3w=,iv:FTCXuFNPpos6FT/tJn/vu9bkwj/2tKlDbRKOINnvtwo=,tag:C9aLKUmiPc5szINR7jR22A==,type:str]
    identity_providers.oidc.hmac.key: ENC[AES256_GCM,data:1hiHTKq+rZWbZGyr8Fk0IRX2I0vpsKThjDtm1nC8kF6zC7v0YXMP2qAksXsgKFtQK+2ZkOksEJGENokYzqQqk/6pH2PhzpAtNa6n8BMsXNqEl8oE3nIeUVXcLTpl/uzt/0zvXT0DByezBwViajwHszDclQin4A5rVqwDlLwDK9g=,iv:OXxRB0bV3L+OQVoe1pOOl0wxSl6F8bFRBgxqM7dgUsM=,tag:jo/jQopmtf4xJOTu0XZ09g==,type:str]
    oidc.jwk.RS256.pem: ENC[AES256_GCM,data:fmWI2g==,iv:KQVI4zq7IuMYw9AqU0h7aJ+dvzeKpdrajB5oPnbvVmc=,tag:CWTgbV3zyIVb1qOHmEgkSA==,type:str]
    oidc.client.immich.value: ENC[AES256_GCM,data:kcnl+yHATrMvGF1mDrY8M294X7e/om3BJBsbEghyty3k0uWb2gxOtrTtDCX86A7kLfi63BEZs8fV5c0DT12oqAALNw7INhuk,iv:narpnLHHDDY8+77kU3Zhbnr6C8u522rCZK4zBFzBhOE=,tag:QdV/X2NUwCRKpFmUmswo4g==,type:str]
    oidc.client.sftpgo.value: ENC[AES256_GCM,data:MAZ+tIJVHYPfNrAsXMqTUk/s+wutK1bEhMoiCX/BgLmqI+97t/N8GJEz4j85q7ofzl2jivysS6wFlvTZlWyrsQ65VRNEyX8K,iv:qTlv8Y5WGPwqHGWZ0UZjDnbDyYD8IDmn8gw89MRYELA=,tag:l8dwg9Erv5iPfU88Evfh5g==,type:str]
    oidc.client.minio.value: ENC[AES256_GCM,data:PGev7SRVUorFSRaeBn5lb1cGVubwrxIEfUY8ee9Hn2dipyYfc8TaMrjrj+gYBlmKm4Dxi7y70yDAF1wCuOjpqgRSyRG70FDk,iv:TGz9uAaWQUynReYVUYTcdVYWPjr02yDrhTayYtGhZdc=,tag:bdfJlIgNk8i5cMFQGGaW9w==,type:str]
    oidc.client.nextcloud.value: ENC[AES256_GCM,data:z6tMzZ0bdub7/v43OSRhz1H530w3xqwIY9MU2JOp2r7woGQv2OdICzRrPPNpn4UGfdp7u8tcy5XOXO34S3EiMoD+hBmwBpvZ,iv:84y+ftWm6SU2VMeT6z78ao490OznH3MVEwbC4E+v0n8=,tag:beESl+IqqJtPBKqBIcyL7A==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMTFxMVhzMkYvTktSOUto
            VUxFQlJsZE0yN0V0Rmxqemx6T0NXajl0NWdJClErb2Y0cjEzOEVyanBDZXQ0WVp5
            dENEZWlxUnR0RHhCQ1ZWTUFjcE5TMFUKLS0tIEJFQVl1ZWdCTVQ1VEwyeDIxVi9B
            bWdMVHcyNXdPTXZ1UlJGRzdhbEJvaWMKMyb4yRBs0SLQQ/H6huEMquV94oRaJ1MG
            wLL4WhdfFfgOlu7gNJ2yxkqPDlvZJFsTsHVdpGMwQCDqBV6XQblAWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T18:24:50Z"
    mac: ENC[AES256_GCM,data:H+DGwq4cgHqbZbWk5rQIP131eAXBtAYHw5lpPoHy1hkQBAoXn10AVqVxemrMwL7G/0ruVdnjD4bvvY1gp/ehEsoBOj0fRsLkDb38407QoI4NST4jnUggG4w3fFZlkZFtRmNaRIm3qu+I0feRVtmbESrTfbzoLrTBKJPoEgq/trA=,iv:4cQDsR8+Pfw7X802TKeTIVHl79K6Wy2eM1U8s9a5Nqc=,tag:2BhKz0SrT6xT3Vbn0n9/Ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
