apiVersion: v1
kind: Secret
metadata:
    name: rg-secrets
    namespace: kube-apps
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cAFTQ1nGqnNQ+8DUFUOOIQ==,iv:AvC+/pVH1K2XH4uCigvBdB3hOXSUpPkDjoN5+d7n9L4=,tag:rdZhQmjSQ4WznOOHiB+iLg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:chtvp3bbzj+Qs4Csd2jXYZh0Aythonhf190rzmvtlXVB,iv:HaxIzTNgm0/UJC/Mb6IR5zs7bRMicw6XSTLzvJEujsA=,tag:RHaws836olsR98LVcwJB8Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:q8qQuQ==,iv:FhwLlTKfGwFFfmIWCtXNfcb9cItkMvpgv2KqY4GjcLo=,tag:NF4aiCogOFiaO04F0qy9qQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TRbVkQ==,iv:h9meYY54EDG3ElBsPP70tIOkRmwXmlihhtIspH2/6ck=,tag:uO3y0cQft91BwT7ZMZOr1g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mSC5tQ==,iv:4udw5VQlXUnTPa7hsi4CMvSsv9Ye6ozwK8hf50diwa8=,tag:j56oMmIjoNWnfG9odT/biQ==,type:str]
    HARDCOVER: ENC[AES256_GCM,data:ZBFxOTeTIUzyuL53FEE1qVzl4NIBhzFGurVz5nSJWERpf8+MpdblKYKd77RaVmy/ECfvK8H7aooHOTORMU26OYCOH8twoDr9D3vgSsVdIWokK1FZJU4EouSYd4GE7Y6DkqVeFGCIcwB6f3n23Xks+NCyLtC4pVvT8UFjWyVslYvd1X7/2vPsytNrCT9J86i8UH6tlez5XCCfpXGXdZ47FM5xE6YkAIaBFGX/eAIxbQxMdtnEpfjvtg1SbOkWKGwWT5GeK+nEqHC7hLvcs+Sx10D07aA08iYLKBQSP+HQOet3DpZ/sIKYnUdXylp1RL0ZQAANCAqPgD1UrhlnWpMufqMHfXtpgwSa5kFcUGVbWNa/CCy35bwQF0tnLnzB1Sz1qnxw3tM70+ygVPu1K7BA1iVaxTngieJ+9LuhNuqFdlqw3PJgHTFP9DMPkr4xARMEARlFkvGtGH7+okOsLewrzf9pqg5B8CpdikJSVs20ivxM4YKcwIsmQu1jBgCwfuT/CqdlWBIJCl63RCKCVeZmf4Pxe5dDeX4ICwSqj2sB/QS3sT2WmUc/rvFX9y/qsjP7SUQAVB156Qyw8MxCdSFKi5T9RG1wrS6EFrAexcRT5WseHTcNUqity6K/D13I8kEXwLLcwtctIdp1Vy4F2xNJss/CD2wSgUe85sVzG97uKbUXsf5wi4VPsw6E0Mn73ksk/pc3YO81UF3jPyIs,iv:exRKFybNyuIkRC2sqQNhvKn+mtduDYusINsvwOAXxcQ=,tag:fOK0erluQwqLchjd2Mt7UA==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweDZZZnNJMFJmUVVRZFlq
            RlpKMFpyZzRQSk1vV1pvVytkNGJtVVUxRXlVCnZnbEZaZG5Ld2FITDlBa1phOXFk
            R0Z5UzlZZkh1QWpCdFNWN0F0cG5nejgKLS0tIG1rL3pDMTZ0TTJBblRxdkQxTVpu
            K3c3dlNlQ0l3VjhacVFONVdIM3BSOXcKwEfiPvFzy9ju8XHXYJLXJpG9El9SlQXc
            XUNzp6zHHcCEIflIpEJssLFuq9zxCFXk3CoFpk/2PNi8MiOIKIl/qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:00:13Z"
    mac: ENC[AES256_GCM,data:5IDs07kfODPQZjeh4h4oAa/aDU3Um+lokSFiO27aozzeIjn0qyAfBnIv/pvMcEldymftPjb2czrMeaduDqWzxKqf1Jm5GGoWZhMhKonp81QQjEPe7pGwbNdPD1n+72HGj+Lh6JKZy29eVF3OXJO4egRSSa4GO+v0cT1/hs09dMo=,iv:7fG/bDmKrFKdUtpzAgTv9/DU+ANeoPeDkldOW0ot0gU=,tag:a7D8cWNIfuRpmrqPD6nSLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
