---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-apps
components:
  - ../../components/common
resources:
  - ./audiobookshelf/ks.yaml
  - ./bookshelf/ks.yaml
  - ./ctcadmin/ks.yaml
  - ./filebrowser/ks.yaml
  - ./huntarr/ks.yaml
  - ./immich/ks.yaml
  - ./nextcloud/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./rreading-glasses/ks.yaml
  - ./rustdesk/ks.yaml
  - ./sftpgo/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./namespace.yaml
