apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:tHC8C5Vn3KNSDw==,iv:R6WsOr+0PP7HzVlVSCctp9E3ApDAxeLdAPKTbTaVdbg=,tag:wGKuowxr1fCfpBMpahiN7Q==,type:str]
    endip: ENC[AES256_GCM,data:bYLz4ompNL5h0rITug==,iv:4TeiODdKt1SHV9R47lJru8hT1j1BYgP4oUQfgqJebY0=,tag:t74wQSSYgYQnGg+9exrVVQ==,type:str]
    pubkey: ENC[AES256_GCM,data:z7mCh9tgq6ALwoBZjJVg3nIKyWmgwI3RCDa/j/zxGLT+5buib8qd99VW15k=,iv:a6wRoLMAHw/4IfBGJ2prws1V1UMEVNmOqxqkQqEg0TQ=,tag:O1yaTATXavBKd7h8XinlFA==,type:str]
    privkey: ENC[AES256_GCM,data:bmUCqtHuDmLhX9tIyCs8VV5vccIIpON1z+UDbg9L6NnwA39QEOG/WYpyKOg=,iv:do1B90ngGoBzI9YpdjJJY7LzFHj+roXnusJbQeP4LGw=,tag:g1ji4I9hxf3hchSVGS+Fog==,type:str]
    wgaddress: ENC[AES256_GCM,data:9Q/OZFdK8rwmy7uF,iv:XoWCAycda0rkhoyL59fDQ1ETBMOKMWktR3VikZ0Bs7c=,tag:dGp16K41biYu9PuVa53H4A==,type:str]
    dns: ENC[AES256_GCM,data:zRXv1S6o7qfJvA==,iv:/CDhga3yW8gS8R3TbvN2MW2/rj01OAWjYXatpMCVnKM=,tag:x+nM/x57E7tzYJvxBlQutQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T13:37:45Z"
    mac: ENC[AES256_GCM,data:46sUJcaMh1dTPwN9D7Q0DyE8AWzvOH1Xg6oU9lZuQwOX1aR4Z69GGytPanMQsOXSuxQ0EpVzIdWkByUMaoaud6XJhNqpEG+Zab2WAnDz76OusTOi6Jqi42dGsGyHddGW0xKrfP2HbD9mJApQUIKZfLZL+l5J5EWRww/tlzaABAs=,iv:QJ+YAX7oneDBY2sraCH83CY92Xjb+GIwLJeuxj/Ddus=,tag:NOakNXXuPMbZIua0/RDD8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
