apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:tHC8C5Vn3KNSDw==,iv:R6WsOr+0PP7HzVlVSCctp9E3ApDAxeLdAPKTbTaVdbg=,tag:wGKuowxr1fCfpBMpahiN7Q==,type:str]
    endip: ENC[AES256_GCM,data:tWTJc2j7H/Ra9lsQ5A==,iv:IvUzvr+R2/ZPh+7YDo/1Nc1As4KCh1ers34XAn2hH3Y=,tag:5Isybd79NOrVch6pESUKSA==,type:str]
    pubkey: ENC[AES256_GCM,data:XODrGFXiHILuHFE8OCgH9yKm3yiOsntudnkZ4CtfQs1WaB3tYIzwoo/juYQ=,iv:ONQ8CzSyQqtULahZPmBI9JcRk0eqEPvFfaZgqHyZwec=,tag:vGnNbSFwOzi/i5erBiXMug==,type:str]
    privkey: ENC[AES256_GCM,data:CFTnqQlwSYV3h/P9sr8E0YDA3aEbNplhw+6wO0IXVvrYlVKcy0p+TgMqMRk=,iv:0IzHP/bEG4TYGCVOBL5tZU4BdUUc0jQl6ThgYhtQH8E=,tag:m4zCQG8qXp5T9fR7e4t58A==,type:str]
    wgaddress: ENC[AES256_GCM,data:9dIOADjhidjhIT4Xeg==,iv:moM2v/FgaT+WNJz5/UU0VUwEekXGgcV44MrD9WefAHM=,tag:FiVB4kIe0WnqVrQmptMUHw==,type:str]
    dns: ENC[AES256_GCM,data:zRXv1S6o7qfJvA==,iv:/CDhga3yW8gS8R3TbvN2MW2/rj01OAWjYXatpMCVnKM=,tag:x+nM/x57E7tzYJvxBlQutQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T16:26:04Z"
    mac: ENC[AES256_GCM,data:A6Uu+sVpsOO1NSgQRZfBQnepVjdk56WJciqrk7e0gcANRHy2zym1uqTF17pwYSHSC+cCh59XgP4OCmvI56SJcWH60BojcDnuX+akRzKIceW9Dvr4LHyMkEBtINU2W+nfOutf6afI1G+0ZRRgPW9pZFLjfrs/uGIsV+gr/fvqiDs=,iv:aEjvwFFyXgNaJ6rV0kaYx+T7hfByHPxxVHNLJTKqQs8=,tag:5EDJrTRQrHTtW7BCl/nnhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
