apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:bqomiKR2M+7+LOyb,iv:hUBQHL5THmZSQwTTvBU4k6F7AGVAkQ+gWunKg0oELjE=,tag:B6EwZSh0rUkpWSH78lQJqQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T17:03:33Z"
    mac: ENC[AES256_GCM,data:FTsPgsBg0WawbaQl/+j625t5Mzj3nT9x59SXgQfhty1jBuWTRTeJ+JA1rzgIJ6impUymFfBq9UBruJjztJZrX3nNtL0n4SPTMJZfJIRmiQ3ppAJfUy0DQJT4v01XudNm3gFW7ryRZyx79k/Rll54LAcK4inWJSC/WEq2eTzcnsE=,iv:nYo639qFgQ+xHso+C/z0OjiEhV3pVGZViDV3HZyTUOU=,tag:DrEWZ3QZIUDCcd1QRbMhHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
