apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:tHC8C5Vn3KNSDw==,iv:R6WsOr+0PP7HzVlVSCctp9E3ApDAxeLdAPKTbTaVdbg=,tag:wGKuowxr1fCfpBMpahiN7Q==,type:str]
    endip: ENC[AES256_GCM,data:mlRX8Ulzo886e6Z8/A==,iv:fXfckhOTuJLJwG7FunwR7/LBBGciTFXyn5WpfG3Mog0=,tag:bsr/Ods9neEZYL8IBM4e0g==,type:str]
    pubkey: ENC[AES256_GCM,data:VuzvBJqg0rRNc8iqme+KQlUmGiCFl4XqTnvC/EdQeIaJ1imv+jwwW8VXqDA=,iv:DgJGYI03BFHzhIPo1pecix7nt6S8YlCDqyWWIu8liqs=,tag:ZxeTmrYEmO6AneENGXRkdQ==,type:str]
    privkey: ENC[AES256_GCM,data:a8jrVMVVMW5ap5ZGVmDN36wJLU/Jps7Bkgbzw+ETp1+pRhAyn+PZdLcvUNU=,iv:fpdf/qbUfByB0Ugwm33Agv9l2kwwqmPtEt5eXUt0R7U=,tag:pJ7jy612XC4Zt/9CsvFiPg==,type:str]
    wgaddress: ENC[AES256_GCM,data:Z82hXrqHgb2toKKrCA==,iv:INodmiCWTwBqIgJ51JoQNg+a6xf82nvy/KbCoK1iDU4=,tag:C7RJPNkcl/7vO4wjADtJNQ==,type:str]
    dns: ENC[AES256_GCM,data:zRXv1S6o7qfJvA==,iv:/CDhga3yW8gS8R3TbvN2MW2/rj01OAWjYXatpMCVnKM=,tag:x+nM/x57E7tzYJvxBlQutQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T16:20:49Z"
    mac: ENC[AES256_GCM,data:Gl0ZPplqsuhQuMHROZPVWKBnp2d9WDp9UDUrgY+fuXP0m9VHCdRBdMBqRKlFtEjjSxSOvIFdlDNou9BtYaYLkAmA4piIPNYRzEVQDKKWy0cT8D7dzC9m//MpSxrQ9KPs2A1XE2sYgoyUq7qocbuLYSgpblIN57QUrBstjRRqNuw=,iv:DyZo9co592l3wCKALnTDHrTtQ8f/VwQIUP+AuoRloAs=,tag:d6W18nXa4NyBBYzTQkCzhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
