apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:SyJToRrnEooVag==,iv:uk7TDIgSJ/eTkb8U2FXjhD6degbEBVzH8xPlub87WNY=,tag:q/g5Kz9QNXyxuTzT/6UuQg==,type:str]
    endip: ENC[AES256_GCM,data:A6eRM4vf6AGBLeVqFw==,iv:xqBYyhJKp0WKhCAaKsTYCS4fKIFN9TKnO19pgpbK6IA=,tag:77UEUA4L0JwEBxqDBQk5Tg==,type:str]
    pubkey: ENC[AES256_GCM,data:N3ug08UVwdSDdwR34BOrhmZHURbh826RCCGdT0HyNixT0veK46Dg+zrDtDM=,iv:soE1ddOiLB+8IizXYE2psHUZGGfUwgmtbEbQtLEbJR0=,tag:1fsXTwKKngNCP6B707eysQ==,type:str]
    privkey: ENC[AES256_GCM,data:hAXSskRfBYe6Bg7zAXDlkLh23JSzG7TrfLz3hAUdj10uAT12TdYVZw5PB5c=,iv:/hXSA1GC5IF5Ekt/ybHyyKs+d6EFJ7r91xACnvOsXF4=,tag:UMVvQh33/42R4CkLnF5cpw==,type:str]
    wgaddress: ENC[AES256_GCM,data:x0eUQrSqBGBG2XWh+w==,iv:v2Cx+kjLV37XUvxHK3/FI8f+btO3WS7lrIb7s/NYEkA=,tag:n31w7K1VDo2pdNHwlnRFbg==,type:str]
    dns: ENC[AES256_GCM,data:zRXv1S6o7qfJvA==,iv:/CDhga3yW8gS8R3TbvN2MW2/rj01OAWjYXatpMCVnKM=,tag:x+nM/x57E7tzYJvxBlQutQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T08:08:52Z"
    mac: ENC[AES256_GCM,data:dFwif87FPNXxWQwa48RcnHXNdCrRja/3ODs6d8Uu4ZqAjC6oS4Xhuxf7+kRZqU/oFODKMZsjXWoNYdGa5eGowfQQQufZEW8ECdjzXHubqr6A55WiZvUcnNHKeSprLNSsxJxMGBvrDbFw8XsdwEINHbFjHWK8c/WTiLGYtjqCr4A=,iv:g7ySlwlhQOSaAUeeScoVSSMm1Oc+6mSWudYkq+aS+JQ=,tag:oohDB5o+0sAUWEzSV+RMZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
