apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:SyJToRrnEooVag==,iv:uk7TDIgSJ/eTkb8U2FXjhD6degbEBVzH8xPlub87WNY=,tag:q/g5Kz9QNXyxuTzT/6UuQg==,type:str]
    endip: ENC[AES256_GCM,data:K5HbhMz7CzbCa4Jd1w==,iv:q9pCgyzpSP9S3cVC8/Y/JBiMDuwyHnVUrmtQ7eETr4E=,tag:ggq0z7OoAuz/K3TdkNMMGA==,type:str]
    pubkey: ENC[AES256_GCM,data:MmnPEtCLKkVctXJP1CpAIDr0rZfSV0GOe+QRY0SyCorzoWvWYjO7DUorXXs=,iv:N07YiyfE+zcdT0Phq28B3sWCTv6rfMJhMWrz/NPheTM=,tag:DuDK4jJKTEa9XbLEgitzEw==,type:str]
    privkey: ENC[AES256_GCM,data:uCoSkqcutMuore/eYmsjVgF75IamV4l77FeGys1ngdULe3ecAb4zehGOZsA=,iv:9ArzejStXqxCJdFV4fQmSplcCmkGNyVmhueYu3htybg=,tag:rHGKv1ZuU3aaB46CrHSZvA==,type:str]
    wgaddress: ENC[AES256_GCM,data:HeNYJ9z3kTZWSmI=,iv:trErJ+vTdrj9A2n7dUrGB/DroZUyPVwpF+KcsMwHWFU=,tag:SS1GO1iRvVdbmblrQSmVOQ==,type:str]
    dns: ENC[AES256_GCM,data:zRXv1S6o7qfJvA==,iv:/CDhga3yW8gS8R3TbvN2MW2/rj01OAWjYXatpMCVnKM=,tag:x+nM/x57E7tzYJvxBlQutQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T08:19:43Z"
    mac: ENC[AES256_GCM,data:PrdwW6NXKKQanLp8a/wBdKB84XoYVAxUGLqy/OA93lFUgCn5EOEAg5pHldET1TGy49aEqcWFNfOTxd+o7KS74infez2V8vHwzR5tTXr1+dODOHJn85dyrJSPFoiX6iun4QAGy4RmSx2q98TOOdvpJmBRvwNTjvcszXMNspSbKX0=,iv:KxM3zLZmKLFkh1Mp6uhaDeSekhOdFSog+LDyQ9FH8pU=,tag:yOYDU9OZDCkOrWvk3N4BSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
