apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:SyJToRrnEooVag==,iv:uk7TDIgSJ/eTkb8U2FXjhD6degbEBVzH8xPlub87WNY=,tag:q/g5Kz9QNXyxuTzT/6UuQg==,type:str]
    endip: ENC[AES256_GCM,data:zC3g3owlnqTw3xzmjw==,iv:3ogBj34Ay0d/+7B3S3ofrC25HIsXnWWpxcaETmA0sfs=,tag:EAt1b8hC2aDTlBnXWrv8Fg==,type:str]
    pubkey: ENC[AES256_GCM,data:CpeF5jwR1ebHTjBkvYfLz4TQZQRstYJo2f0nDPDaERgufxZkKiVKt3rJGmE=,iv:gUfDCkYI9EJxNMO53X6qobzgfH4kuU/pJC/Y7HpvYi4=,tag:2bjYdHgxZoEh5nXQkfeo8w==,type:str]
    privkey: ENC[AES256_GCM,data:QsEcD5jHHXfPpYGiQ1yCq+HkzHGA8IBM8G5MV4qOQdKvcEN2iCEGPx8fPzs=,iv:wvhuX42yGM901S68wq9doohGS+mq1A2pjQzHf/hmQ3Y=,tag:YM+PK+f8CWdzGZjiRnubhA==,type:str]
    wgaddress: ENC[AES256_GCM,data:vxIlx6PD81qzx+nI,iv:Yg4e6t8QMpH/BEC3Vk7gKIt5czFim0PU2gQFFDuiZss=,tag:lY+sZr0YeSttD+fN2NjXUg==,type:str]
    dns: ENC[AES256_GCM,data:zRXv1S6o7qfJvA==,iv:/CDhga3yW8gS8R3TbvN2MW2/rj01OAWjYXatpMCVnKM=,tag:x+nM/x57E7tzYJvxBlQutQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T22:13:39Z"
    mac: ENC[AES256_GCM,data:qnaQU44Y1mTmPcATtMhvxzbidPp7KkK1sC31VmpIt1S2xtz2acuYGkaJML4pEkKbBCZRXa3NIBB9Gott3E11h0m+VAUJjFeLItNKvefVeZ1RDH/5fa4a6g+0VOkpCFW9Oz1xBfmmesh7Aa3AL8nFQyonz8aO6IXjG6jXEMLTemU=,iv:3Na+ii4rhulNHlcnT1GWXcOt1faMQhRPjdy39jN01S8=,tag:YPM5yljJRmEz65wj6ZpWhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
