apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
stringData:
    username: ENC[AES256_GCM,data:TqWTj8nFmQ0=,iv:tuxZ2/+S+BYrSNrgziaJr1s3q9Lraz+u/JxyY4yv67Y=,tag:9TEMNodfYaKZA1OBnbnPHw==,type:str]
    password: ENC[AES256_GCM,data:6YD103baLMaUTfyi,iv:F7RVLjX+fXCYYfCOmu+aoAvKeRap1A95XzpY4j9VKpY=,tag:dlX/d1wOiMVkJN1NaaS1vw==,type:str]
    server: ENC[AES256_GCM,data:SyJToRrnEooVag==,iv:uk7TDIgSJ/eTkb8U2FXjhD6degbEBVzH8xPlub87WNY=,tag:q/g5Kz9QNXyxuTzT/6UuQg==,type:str]
    endip: ENC[AES256_GCM,data:VOtMs7ALZqfaIMh36w==,iv:UszDLMp2X9ZXWfUMOPFlSjluJBioWMq2bpthQl8+Lxg=,tag:2kxjtKEBQXsJJPr8fpAwSQ==,type:str]
    pubkey: ENC[AES256_GCM,data:o0ROROEdYisxZjhPDb/hKCIXkWCa5kTpe7KePWNqw+G6x3RJHOKQ4Rvj9Qw=,iv:t634//ReGmU9h2ZIYVni6zrIyNdK/TlF/sFu/U3J/Z0=,tag:oH0TVYAfjOlY7IKoI5B/2Q==,type:str]
    privkey: ENC[AES256_GCM,data:Xgwnv9mJa+uMJo2rujF0Xcer0dTopk7DrDEvZRUHAAOUvfnWJtF2zfirrn8=,iv:N7X9X+kmFpK0WyUNzG7kzAWvl4yT3pf0ZCUTQ62e7ak=,tag:eN+sjq/LAgiGHkkQJgVbwg==,type:str]
    wgaddress: ENC[AES256_GCM,data:/I7N6oOo6lVoE3Cx,iv:yAabjKJcChe7HphWyB6clnT06s164EdQQvg+hXpmKPs=,tag:rQuNnuM1gW46P0/Jm9NuyQ==,type:str]
    dns: ENC[AES256_GCM,data:zRXv1S6o7qfJvA==,iv:/CDhga3yW8gS8R3TbvN2MW2/rj01OAWjYXatpMCVnKM=,tag:x+nM/x57E7tzYJvxBlQutQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSHpxaDhHRHMxY3ZTVit2
            YVl6Vk5ySkkxTTd5YXM5ZVR0cXhxNWZuZUc0CjhtTUJJQWZJb1MwVldGaElzWllr
            cUVvdFNqNmRMZEloaXdFcDJpQWxBakEKLS0tIGV0NmM0WTZuSU13OC9zVStMdFl4
            MVIwNCs0SlpKQ2JhaktjSm50anFxVlEK3HmAKnNB8GfqPcA2QUGC63qsyTak+s65
            i1qg5fIr56dgCkmBffi8xtgqMzhMWnlLO4ECCcxVUdbTR6ARebZ6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T19:48:33Z"
    mac: ENC[AES256_GCM,data:evN81+V8ota/bibretINFxziwDGIwg9RMQ9P7uTx+ZqBEdt4CO4gUU4nPcmw9CZNHWJQxXhZdixK6dVztvVsTTRZ5eb2Q4Z8FTGk1MeaoGz67WLe11fwgiT3DqLfrXYFuBGylh72VxDuNHA1GSvH/nH2gGTv6Xjt4GMJg8mJ3q0=,iv:Y1T+n5/8vFB9Rn/GhfR8TDyZSXahEE2K6NtUYVZih70=,tag:qeMOR9HJpplEjy2Vqs+PCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
