---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: win10
  namespace: virt
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: kubevirt
      interval: 30m
  dependsOn:
    - name: kubevirt
      namespace: virt
  values:
    resources:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: win10-root
        spec:
          storageClassName: vm-apps
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
      - apiVersion: kubevirt.io/v1
        kind: VirtualMachine
        metadata:
          name: win10
          namespace: virt
          annotations:
            kubevirt.io/keep-launcher-alive-after-failure: "true"
        spec:
          runStrategy: Manual
          template:
            metadata:
              labels:
                kubevirt.io/os: win10
                kubevirt.io/vm: win10
                kubevirt.io/domain: win10
            spec:
              domain:
                clock:
                  timezone: ${TIMEZONE}
                cpu:
                  model: host-passthrough
                  sockets: 1
                  maxSockets: 1
                  cores: 2
                  threads: 2
                devices:
                  # hostDevices:
                  # - deviceName: kubevirt.io/inelo
                  #   name: inelo
                  # - deviceName: kubevirt.io/token
                  #   name: token
                  disks:
                    - name: root
                      disk:
                        bus: virtio
                firmware:
                  uuid: 0fc5e6a0-0ef4-4919-8321-07ed0caf3a5c
                  bootloader:
                    efi:
                      secureBoot: false
                resources: {}
                memory:
                  guest: 8Gi
              volumes:
                - name: root
                  persistentVolumeClaim:
                    claimName: win10-root
      - apiVersion: v1
        kind: Service
        metadata:
          annotations:
            lbipam.cilium.io/ips: 192.168.1.140
          labels:
            kubevirt.io/vm: win10
          name: win10
        spec:
          ports:
          - name: nx
            port: 4000
            protocol: TCP
            targetPort: 4000
            NodePort: 4000
          selector:
            vm.kubevirt.io/name: win10
          type: LoadBalancer
