---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cdi
  namespace: virt
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: cdi
      interval: 30m
  values:
    resources:
      - apiVersion: cdi.kubevirt.io/v1beta1
        kind: CDI
        metadata:
          name: cdi
        spec:
          config:
            featureGates:
            - HonorWaitForFirstConsumer
            - WebhookPvcRendering
            - BlockVolume
          imagePullPolicy: IfNotPresent
          infra:
            nodeSelector:
              kubernetes.io/os: linux
            tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
          workload:
            nodeSelector:
              kubernetes.io/os: linux
      - apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: cdi
        spec:
          hostnames: ["cdi.${SECRET_DOMAIN}"]
          parentRefs:
            - name: internal
              namespace: network
              sectionName: http
          rules:
            - backendRefs:
                - name: cdi-uploadproxy
                  namespace: virt
                  port: 443
