---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cdi
  namespace: virt
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: cdi
      interval: 30m
  values:
    resources:
      - apiVersion: cdi.kubevirt.io/v1beta1
        kind: CDI
        metadata:
          name: cdi
        spec:
          config:
            featureGates:
            - HonorWaitForFirstConsumer
            - WebhookPvcRendering
            - BlockVolume
          imagePullPolicy: IfNotPresent
          infra:
            nodeSelector:
              kubernetes.io/os: linux
            tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
          workload:
            nodeSelector:
              kubernetes.io/os: linux
      - apiVersion: v1
        kind: Service
        metadata:
          annotations:
            lbipam.cilium.io/ips: 192.168.1.141
          labels:
            kubevirt.io/vm: cdi-uploadproxy
          name: cdi-uploadproxy
        spec:
          ports:
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          type: LoadBalancer
